version: '3'
services:
  nginx:
    container_name : nginx
    build: ./requirement/nginx/
    restart: always
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - www-data:/var/www/html
    networks:
      - inception
  wordpress:
    container_name : wordpress
    build: ./requirement/wordpress
    restart: always
    env_file :
      - .env
    depends_on:
      - mariadb
    volumes:
      - www-data:/var/www/html
    networks:
      - inception
  mariadb:
    container_name : mariadb
    build: ./requirement/mariadb
    restart: always
    env_file :
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql/
    networks:
      - inception
volumes:
  mariadb_data :
    driver : local
    driver_opts :
      device : /home/mobo/data/database
      o : bind
      type : none
  www-data :
    driver : local
    driver_opts :
      device : /home/mobo/data/wordpress
      o : bind
      type : none
networks :
  inception:
    driver: bridge
